export const QUERY_DESC = {
    INIT_AUTH: 'Send a phone verification call',
    VERIFY_OTP_LOGIN: 'Verify and login or signup',
    LOGOUT: 'User logout',
    SAVE_PROFILE_INFO: 'Save profile info, firstname, lastname, photo, email, city',
    UPLOADED_DOCS_INFO: 'Get a uploaded docs info',
    SAVE_DOCS: 'Save a verfication docs info',
    USER_INFO: 'Get User info',
    ADMIN_LOGIN: 'Admin Login',
    CREATE_ORDER: 'Create a order',
    GET_PACKAGE: 'Get current package info',
    CONFIRM_PACKAGE: 'Package pickup confirm by partner.',
    GET_ACTIVE_WORK: 'Get partner active work.',
    GET_WALLET_INFO: 'Get wallet info.',
    PINCODE_SERVICEABILITY: 'Check pincode serviceability.',
}